version: "3.8"
services:
    cartapi:
        # image: shopping-cart 
        restart: always
        build:
            dockerfile: Dockerfile
            context: .
        env_file:
            - docker.env
        depends_on: 
            - mysql
        ports:
            - "3000:3000"
        networks:
            - webnet

    mysql:
        restart: always
        image: mysql:8.0.27
        ports:
            - "3307:3307"
        volumes:
            - ./database/data:/var/lib/mysql #it can be deleted when not needed anymore
        expose:
            - 3307
        environment: 
            - MYSQL_ROOT_PASSWORD=cartpassword
            - MYSQL_USER=cartuser
            - MYSQL_PASSWORD=cartpassword
            - MYSQL_DATABASE=cart
            - MYSQL_TCP_PORT=3307
        networks:
          - webnet
networks:
  webnet: